default: &default
  adapter: postgresql
  encoding: unicode
  database: friendapp
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: friendapp_dev
  username: postgres
  host: localhost
  password: qweasd123

test:
  <<: *default
  database: friendappapp_test
  username: postgres
  host: localhost
  password: qweasd123

production:
  <<: *default
  database: friendapp_production
  # username: hadiapp
  # password: <%= ENV['HADIAPP_DATABASE_PASSWORD'] %>