default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  # <<: *default
  adapter: sqlite3
  database: friendsapp_dev
 
test:
  adapter: sqlite3
  database: friendsapp_dev

production:
  <<: *default
  database: friendsapp_production
  username: postgres
  password: <%= ENV['PGSQL_DATABASE_PASSWORD'] %>