# default: &default
#   adapter: postgresql
#   encoding: unicode
 
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  database: friendsapp_dev
  encoding: unicode
 
test:
  adapter: sqlite3
  database: friendsapp_test
  encoding: unicode

production:
  adapter: postgresql
  database: friendsapp_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV['PGSQL_DATABASE_PASSWORD'] %>
  encoding: unicode